name             'spark'
maintainer       'Michal Klos'
maintainer_email 'mklos@localytics.com'
license          'Apache 2.0'
description      'Install and configure Apache Spark for Localytics'
long_description ''
version          '0.1.1'
depends          'ly-base','~> 0.2.7'
depends          'scala'
provides         'spark'
provides         'spark::master'
provides         'spark::worker'


supports 'ubuntu', '>= 14.04'
