name             'spark'
maintainer       'Antonin Amand'
maintainer_email 'antonin.amand@gmail.com'
license          'MIT'
description      'Install and configure Apache spark'
long_description ''
version          '0.1.0'
depends          'scala'
provides         'spark'
provides         'spark::master'
provides         'spark::slave'
